### ISSUE TITLE
The TIRA platform

### ISSUE THREAD

**Issue by dan-zeman** [ufal/conll2017#10]
The TIRA platform, recommended for evaluation, is at http://www.tira.io/. We need to know how it works. And it would be nice to know it even before we submit the proposal. Unfortunately, I don't see documentation at the website, and I don't see any playground to just create a toy task and explore. Instead, one has to write an e-mail to tira@webis.de and ask them first to host the task. Should we do the step now?

I don't know whether
- the participant creates a virtual machine containing a main entry script, then I will run the virtual machine, add test data and run the script, then collect results and evaluate them; OR
- the participant has to get the blind test data from me and include it with his software in the VM, then I will run it, collect results and evaluate; OR
- endless other possibilities, with varying degree of the participant's ability to see and influence things.

**Comment by dan-zeman** [comment]
Related: We will have to specify the maximum time any system is given to process the test data. Obviously we cannot wait several weeks for the output. But what is a reasonable limit? Some test data are large and 1 hour may not be enough. On the other hand, we probably don't want to go over 24 hours, do we?

Also, there should be a mechanism for the participants to learn that something technical went wrong (e.g. arguments on command line) and their system did not run as expected. In particular, if the system does not crash, its CoNLL-U output is formally valid, but it does not contain all sentences, or the words are mismatched, that might be due to a trivial bug that can be easily fixed and the participant should have the chance to fix it, instead of their system being automatically removed from evaluation.

**Comment by dan-zeman** [comment]
I found at least some hints here:
http://conll15st.blogspot.com/

**Comment by foxik** [comment]
I am happy to help with the technical stuff.

The blogspot seems to answer nearly all questions:
- the users will create the VM, without the data
- the users will run the parser, either on training/development data (where they can see anything), or on the testing data (then they do not see nearly nothing, just that the output format is wrong)
- therefore, we probably do not need to bother much with the time limit of the evaluation -- it is responsibility of the participants to have processed data ready in the deadline

**Comment by dan-zeman** [comment]
OK, closing for now. Let's wait until the proposal is accepted and then we will contact the TIRA administrator and ask for help.
