### ISSUE TITLE
UDError: Cannot parse HEAD '_'

### ISSUE THREAD

**Issue by happypetewht** [ufal/conll2017#22]
Hi. I am new to conll2017 and are trying to use evaluation scripts and udpipe for my dependency parsing task. I am experimenting with the gold and test conllu files. But I can not load test file but gold file. Do you guys know what happens? I got errors. Thank you for the help. 

![image](https://user-images.githubusercontent.com/26719562/133491652-62596b11-209a-4518-a459-9b975ac38ca4.png)

**Comment by dan-zeman** [comment]
Are you sure that the CoNLL-U file that you are trying to load contains the syntactic annotation? It looks like you are trying to evaluate the blind test data, which serves as the input for a parser and it cannot be evaluated until it has been parsed.

**Comment by happypetewht** [comment]
This is part of my test CoNLL-U file:

# newdoc
# newpar
# sent_id = 1
# text = What if Google Morphed Into GoogleOS?
1	What	what	PRON	WP	PronType=Int	_	_	_	_
2	if	if	SCONJ	IN	_	_	_	_	_
3	Google	Google	PROPN	NNP	Number=Sing	_	_	_	_
4	Morphed	Morphed	PROPN	NNP	Number=Sing	_	_	_	_
5	Into	Into	PROPN	NNP	Number=Sing	_	_	_	_
6	GoogleOS	GoogleOS	PROPN	NNP	Number=Sing	_	_	_	SpaceAfter=No
7	?	?	PUNCT	.	_	_	_	_	_

# sent_id = 2
# text = What if Google expanded on its search-engine (and now e-mail) wares into a full-fledged operating system?
1	What	what	PRON	WP	PronType=Int	_	_	_	_
2	if	if	SCONJ	IN	_	_	_	_	_
3	Google	Google	PROPN	NNP	Number=Sing	_	_	_	_
4	expanded	expand	VERB	VBD	Mood=Ind|Tense=Past|VerbForm=Fin	_	_	_	_
5	on	on	ADP	IN	_	_	_	_	_
6	its	its	PRON	PRP$	Gender=Neut|Number=Sing|Person=3|Poss=Yes|PronType=Prs	_	_	_	_
7	search	search	NOUN	NN	Number=Sing	_	_	_	SpaceAfter=No
8	-	-	PUNCT	HYPH	_	_	_	_	SpaceAfter=No
9	engine	engine	NOUN	NN	Number=Sing	_	_	_	_
10	(	(	PUNCT	-LRB-	_	_	_	_	SpaceAfter=No
11	and	and	CCONJ	CC	_	_	_	_	_
12	now	now	ADV	RB	_	_	_	_	_
13	e-mail	e-mail	NOUN	NN	Number=Sing	_	_	_	SpaceAfter=No
14	)	)	PUNCT	-RRB-	_	_	_	_	_
15	wares	ware	NOUN	NNS	Number=Plur	_	_	_	_
16	into	into	ADP	IN	_	_	_	_	_
17	a	a	DET	DT	Definite=Ind|PronType=Art	_	_	_	_
18	full	full	ADJ	JJ	Degree=Pos	_	_	_	SpaceAfter=No
19	-	-	PUNCT	HYPH	_	_	_	_	SpaceAfter=No
20	fledged	fledge	ADJ	JJ	Degree=Pos	_	_	_	_
21	operating	operating	NOUN	NN	Number=Sing	_	_	_	_
22	system	system	NOUN	NN	Number=Sing	_	_	_	SpaceAfter=No
23	?	?	PUNCT	.	_	_	_	_	_
 

The gold file is 

# newdoc id = weblog-blogspot.com_zentelligence_20040423000200_ENG_20040423_000200
# sent_id = weblog-blogspot.com_zentelligence_20040423000200_ENG_20040423_000200-0001
# text = What if Google Morphed Into GoogleOS?
1	What	what	PRON	WP	PronType=Int	0	root	_	_
2	if	if	SCONJ	IN	_	4	mark	_	_
3	Google	Google	PROPN	NNP	Number=Sing	4	nsubj	_	_
4	Morphed	morph	VERB	VBD	Mood=Ind|Tense=Past|VerbForm=Fin	1	advcl	_	_
5	Into	into	ADP	IN	_	6	case	_	_
6	GoogleOS	GoogleOS	PROPN	NNP	Number=Sing	4	obl	_	SpaceAfter=No
7	?	?	PUNCT	.	_	4	punct	_	_

# sent_id = weblog-blogspot.com_zentelligence_20040423000200_ENG_20040423_000200-0002
# text = What if Google expanded on its search-engine (and now e-mail) wares into a full-fledged operating system?
1	What	what	PRON	WP	PronType=Int	0	root	_	_
2	if	if	SCONJ	IN	_	4	mark	_	_
3	Google	Google	PROPN	NNP	Number=Sing	4	nsubj	_	_
4	expanded	expand	VERB	VBD	Mood=Ind|Tense=Past|VerbForm=Fin	1	advcl	_	_
5	on	on	ADP	IN	_	15	case	_	_
6	its	its	PRON	PRP$	Gender=Neut|Number=Sing|Person=3|Poss=Yes|PronType=Prs	15	nmod:poss	_	_
7	search	search	NOUN	NN	Number=Sing	9	compound	_	SpaceAfter=No
8	-	-	PUNCT	HYPH	_	9	punct	_	SpaceAfter=No
9	engine	engine	NOUN	NN	Number=Sing	15	compound	_	_
10	(	(	PUNCT	-LRB-	_	9	punct	_	SpaceAfter=No
11	and	and	CCONJ	CC	_	13	cc	_	_
12	now	now	ADV	RB	_	13	advmod	_	_
13	e-mail	e-mail	NOUN	NN	Number=Sing	9	conj	_	SpaceAfter=No
14	)	)	PUNCT	-RRB-	_	15	punct	_	_
15	wares	wares	NOUN	NNS	Number=Plur	4	obl	_	_
16	into	into	ADP	IN	_	22	case	_	_
17	a	a	DET	DT	Definite=Ind|PronType=Art	22	det	_	_
18	full	full	ADV	RB	_	20	advmod	_	SpaceAfter=No
19	-	-	PUNCT	HYPH	_	20	punct	_	SpaceAfter=No
20	fledged	fledged	ADJ	JJ	Degree=Pos	22	amod	_	_
21	operating	operating	NOUN	NN	Number=Sing	22	compound	_	_
22	system	system	NOUN	NN	Number=Sing	4	obl	_	SpaceAfter=No
23	?	?	PUNCT	.	_	4	punct	_	_

I am not sure of the difference.

**Comment by happypetewht** [comment]
This is test file 

![image](https://user-images.githubusercontent.com/26719562/133497939-214644dc-1627-4920-a82f-90db6de6427b.png)


This is gold file :

![image](https://user-images.githubusercontent.com/26719562/133498059-33cfe26c-68c8-45e9-b9a4-0eaf956930e0.png)

I assume both are parsed.

**Comment by dan-zeman** [comment]
I see. The test file is not a valid CoNLL-U file and it would have been rejected in the CoNLL 2017 shared task. There is only morphological but no syntactic annotation (the underscores in the seventh and the eighth columns, HEAD and DEPREL).

If you are not interested in syntax and only want to evaluate morphology with the official evaluation script, you have to put some fake tree structure there and make the file valid. E.g., the first node in each sentence could have HEAD=0 and DEPREL="root", and all other nodes could have HEAD=1 and DEPREL="dep".

**Comment by happypetewht** [comment]
Thank you so much. I will change that.
