### ISSUE TITLE
Task definition

### ISSUE THREAD

**Issue by jnivre** [ufal/conll2017#5]
We need to define exactly what should be output (and scored) by the parsers. I assume that, in addition to dependencies, parsers should output part-of-speech tags and morphological features. 

But what about lemmas? On the one hand, they are part of the UD representation. On the other hand, they are language-specific and not consistently defined across languages. I would be inclined to leave them out of the required output, but participants would of course be free to include them in their systems if they think it improves performance.

Another issue concerns language-specific tags, which are available for many languages and which often improve performance on those languages. Are these to be banned in the interest of universality or are they fair game for improving performance although not part of the required output?

**Comment by foxik** [comment]
We thought we are talking about parsing only -- therefore, only `head` and `deprel` would be required (evaluated). Out point was that requiring joint tagging and parsing would be too big task. The tagging and parsing are also not so similar, so many people would probably develop two systems. Also it would make it more difficult to compare contestant systems. We therefore proposed only LAS as an evaluation metrics (modulo changes discussed in #6), to have only one measure, and to require only `head` and `deprel`.

Do you think we should include the tagging (i.e., POSTAGs + FEATs)? That would make the task definitely more complex, but probably more interesting :-) If we are at it, we could also require LEMMAs...

To the rest of you questions: I think we should allow the participants to use any anotation presentin the UD data, i.e., both lemmas and XPOSTAGs if present.

**Comment by jnivre** [comment]
Maybe it is a good idea to consider parsing only, in order to keep things clear and simple. But then it is even more important that the main evaluation metric focuses on dependencies that are (by and large) cross-linguistically stable (see issue #6), since one of the key ideas in UD is that function word dependencies often correspond to morphological features in other languages. Therefore, it would not be in the UD spirit to score one and not the other.

**Comment by fginter** [comment]
Hi

I think people should be able to use anything they like from the training data, also `XPOS`. Of course it won't be there in the test data and it won't be in the training data for many languages.

I would not complicate things in the first round of the task too much, and only go with `HEAD+DEPREL` and nothing else. There is of course the risk of CoNLL replying _it's the old task with more data, come up with something new and more challenging_. So we need to really stress the novelty here: 40+ compulsory languages, surprise language, etc... I hope that would do.

-F

**Comment by dan-zeman** [comment]
I am tentatively closing this issue as I believe we have reached a consensus. Note that besides HEAD and DEPREL we will also evaluate FORM, i.e. tokenization, because we can hardly avoid it.

Only universal part of DEPREL (before ":") will be evaluated.

Everything else (LEMMA, UPOS, XPOS, FEATS, language-specific part of DEPREL, DEPS, MISC) can be used by the systems during training, can be output by the systems, can be even reported by us if found interesting, but will not count towards the main evaluation metric.
