### ISSUE TITLE
Token count for evaluation corpus

### ISSUE THREAD

**Issue by ftyers** [ufal/conll2017#7]
The 10,000 token count for the evaluation corpus, does that include punctuation tokens ? How should it be calculated ?

**Comment by martinpopel** [comment]
I think it is 10,000 (syntactic) words, not 10,000 tokens. So including punctuation and "vámonos" counts as two words.

**Comment by ftyers** [comment]
So, e.g. something like:

```
$ cat bxr-ud.conllu | grep -v '^$' | grep -v '^#' | wc -l
2974
```

**Comment by martinpopel** [comment]
You need to exclude the multiword tokens (where the first column contains a dash), so rather
`cat bxr-ud.conll | ack '^\d+\t' | wc -l`
(I prefer [ack](http://beyondgrep.com/) over `grep`.)

**Comment by ftyers** [comment]
Great! thanks :)
